# Database
API_ADAPTER: mysql2
API_DB: development
API_DB_HOST: localhost
API_DB_PASSWORD: '12341234'
API_DB_PORT: '3300'
API_DB_USERNAME: root

# Secret key for Devise and Rails security
API_SECRET_KEY_BASE: bobross1234bobross1234bobross1234bobross1234bobross1234

# Capistrano deployment log path
API_DEPLOYED_REVISION_LOG: /path/to/app/revisions.log

# Alma
ALMA_OPEN_HOURS_URL: 'https://url/to/alma/api'
ALMA_SPECIAL_HOURS_URL: 'https://url/to/special/hours/alma/api'
ALMA_API_KEY: 'almaapikey123'
ALMA_CACHED_FOR: '720'
