# osulp-api secrets
development:
  secret_key_base: bobross1234bobross1234bobross1234bobross1234bobross1234
test:
  secret_key_base: bobross1234bobross1234bobross1234bobross1234bobross1234
staging:
  secret_key_base: <%= ENV["API_SECRET_KEY_BASE"] %>
production:
  secret_key_base: <%= ENV["API_SECRET_KEY_BASE"] %>
